
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('stories').del()
    .then(function () {
      // Inserts seed entries
      return knex('stories').insert([
        {id: 1, story_name: 'My trip to Italy', story_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum vitae sapien pellentesque habitant morbi. Pellentesque elit ullamcorper dignissim cras tincidunt. Urna nunc id cursus metus aliquam eleifend. Id aliquet lectus proin nibh nisl condimentum id. Eget felis eget nunc lobortis. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Vitae auctor eu augue ut lectus arcu. Maecenas volutpat blandit aliquam etiam erat velit. Sagittis eu volutpat odio facilisis mauris sit amet massa. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Fusce id velit ut tortor pretium viverra. Faucibus purus in massa tempor nec feugiat nisl pretium. Ornare suspendisse sed nisi lacus sed viverra. Nisi quis eleifend quam adipiscing. Nisl vel pretium lectus quam id leo in. Auctor urna nunc id cursus metus aliquam eleifend.", user_id: 2},
        {id: 2, story_name: 'My trip to Fire State Park', story_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa sed elementum tempus egestas sed sed risus pretium quam. Tristique senectus et netus et malesuada fames ac. Tempor orci dapibus ultrices in iaculis. Fames ac turpis egestas integer eget aliquet. Aliquet porttitor lacus luctus accumsan. Aenean euismod elementum nisi quis eleifend quam adipiscing. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Nisl pretium fusce id velit ut tortor pretium. Placerat vestibulum lectus mauris ultrices eros. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Ipsum consequat nisl vel pretium lectus. Donec ac odio tempor orci dapibus ultrices. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Mus mauris vitae ultricies leo integer malesuada nunc vel. Lorem sed risus ultricies tristique nulla. Amet cursus sit amet dictum. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet.", user_id: 3},
        {id: 3, story_name: 'My trip to Greece', story_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fames ac turpis egestas sed tempus urna et pharetra pharetra. Commodo elit at imperdiet dui accumsan sit. In arcu cursus euismod quis viverra nibh cras. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Metus aliquam eleifend mi in nulla posuere. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Rutrum quisque non tellus orci ac auctor augue. Lobortis mattis aliquam faucibus purus in massa tempor. Dignissim cras tincidunt lobortis feugiat. In iaculis nunc sed augue lacus viverra vitae.", user_id: 1}
      ]);
    });
};
